import { database, client } from "./src/database";

async function main() {
  client.connect();
  // clear logs and blacklist collections
  await database.collection("logs").deleteMany({});
  await database.collection("blacklist").deleteMany({});
  console.log("Database cleared successfully 🎉");

  // add some data to the logs collection
  await database.collection("logs").insertMany([
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "192.168.1.1",
        country: "United States",
        city: "New York",
        flag: "🇺🇸",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "203.0.113.45",
        country: "India",
        city: "Mumbai",
        flag: "🇮🇳",
      },
      timestamp: new Date(1479612800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "198.51.100.85",
        country: "France",
        city: "Paris",
        flag: "🇫🇷",
      },
      timestamp: new Date(1624312800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "93.184.216.34",
        country: "United Kingdom",
        city: "London",
        flag: "🇬🇧",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "12.34.56.78",
        country: "Canada",
        city: "Toronto",
        flag: "🇨🇦",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "172.16.254.1",
        country: "Japan",
        city: "Tokyo",
        flag: "🇯🇵",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "123.45.67.89",
        country: "Australia",
        city: "Sydney",
        flag: "🇦🇺",
      },
      timestamp: new Date(1625012800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "89.67.45.23",
        country: "Brazil",
        city: "São Paulo",
        flag: "🇧🇷",
      },
      timestamp: new Date(1625012800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "54.32.11.99",
        country: "Germany",
        city: "Berlin",
        flag: "🇩🇪",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "33.22.11.100",
        country: "Russia",
        city: "Moscow",
        flag: "🇷🇺",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "101.202.103.44",
        country: "China",
        city: "Shanghai",
        flag: "🇨🇳",
      },
      timestamp: new Date(1679612800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "22.33.44.55",
        country: "Italy",
        city: "Rome",
        flag: "🇮🇹",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "211.22.33.44",
        country: "South Korea",
        city: "Seoul",
        flag: "🇰🇷",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "55.66.77.88",
        country: "Netherlands",
        city: "Amsterdam",
        flag: "🇳🇱",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "44.33.22.11",
        country: "Sweden",
        city: "Stockholm",
        flag: "🇸🇪",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "98.76.54.32",
        country: "South Africa",
        city: "Cape Town",
        flag: "🇿🇦",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "212.11.22.33",
        country: "Saudi Arabia",
        city: "Jeddah",
        flag: "🇸🇦",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "77.88.99.100",
        country: "Mexico",
        city: "Mexico City",
        flag: "🇲🇽",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "33.44.55.66",
        country: "United Arab Emirates",
        city: "Dubai",
        flag: "🇦🇪",
      },
      timestamp: new Date(1624012800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "77.66.55.44",
        country: "Spain",
        city: "Barcelona",
        flag: "🇪🇸",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "88.99.77.66",
        country: "Turkey",
        city: "Istanbul",
        flag: "🇹🇷",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "44.55.66.77",
        country: "Argentina",
        city: "Buenos Aires",
        flag: "🇦🇷",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "33.22.11.10",
        country: "Singapore",
        city: "Singapore",
        flag: "🇸🇬",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "123.234.56.78",
        country: "New Zealand",
        city: "Auckland",
        flag: "🇳🇿",
      },
      timestamp: new Date(1679612800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "55.44.33.22",
        country: "Portugal",
        city: "Lisbon",
        flag: "🇵🇹",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "sql-injection",
      message: "Potential SQL Injection detected.",
      attacker: {
        ip: "77.88.99.101",
        country: "Malaysia",
        city: "Kuala Lumpur",
        flag: "🇲🇾",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "brute-force",
      message: "Potential brute force attack detected.",
      attacker: {
        ip: "102.103.104.105",
        country: "Pakistan",
        city: "Karachi",
        flag: "🇵🇰",
      },
      timestamp: new Date(),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "xss",
      message: "Potential XSS detected.",
      attacker: {
        ip: "202.203.204.205",
        country: "Indonesia",
        city: "Jakarta",
        flag: "🇮🇩",
      },
      timestamp: new Date(1680012800000),
    },
    {
      serverID: process.env.SERVER_ID,
      type: "dos",
      message: "Potential DoS attack detected.",
      attacker: {
        ip: "106.107.108.109",
        country: "Vietnam",
        city: "Hanoi",
        flag: "🇻🇳",
      },
      timestamp: new Date(),
    },
  ]);

  // add some data to the blacklist collection
  await database.collection("blacklist").insertMany([
    {
      ip: "67.215.65.139",
      reason: "Repeated XSS attacks",
      country: "Saudi Arabia",
      city: "Riyadh",
      flag: "🇸🇦",
      timestamp: new Date(),
    },
    {
      ip: "71.170.207.19",
      reason: "SQL Injection attempt",
      country: "Germany",
      city: "Berlin",
      flag: "🇩🇪",
      timestamp: new Date(),
    },
    {
      ip: "83.169.230.83",
      reason: "Repeated XSS attacks",
      country: "Russia",
      city: "Moscow",
      flag: "🇷🇺",
      timestamp: new Date(),
    },
    {
      ip: "192.168.1.1",
      reason: "DoS attack detected",
      country: "United States",
      city: "New York",
      flag: "🇺🇸",
      timestamp: new Date(),
    },
    {
      ip: "203.0.113.45",
      reason: "XSS attack detected",
      country: "India",
      city: "Mumbai",
      flag: "🇮🇳",
      timestamp: new Date(),
    },
    {
      ip: "198.51.100.85",
      reason: "SQL Injection attempt",
      country: "France",
      city: "Paris",
      flag: "🇫🇷",
      timestamp: new Date(),
    },
    {
      ip: "93.184.216.34",
      reason: "Brute force login attempts",
      country: "United Kingdom",
      city: "London",
      flag: "🇬🇧",
      timestamp: new Date(),
    },
    {
      ip: "12.34.56.78",
      reason: "SQL Injection attempt",
      country: "Canada",
      city: "Toronto",
      flag: "🇨🇦",
      timestamp: new Date(),
    },
    {
      ip: "172.16.254.1",
      reason: "DoS attack detected",
      country: "Japan",
      city: "Tokyo",
      flag: "🇯🇵",
      timestamp: new Date(),
    },
    {
      ip: "123.45.67.89",
      reason: "Brute force login attempts",
      country: "Australia",
      city: "Sydney",
      flag: "🇦🇺",
      timestamp: new Date(),
    },
    {
      ip: "89.67.45.23",
      reason: "XSS attack detected",
      country: "Brazil",
      city: "São Paulo",
      flag: "🇧🇷",
      timestamp: new Date(),
    },
    {
      ip: "54.32.11.99",
      reason: "DoS attack detected",
      country: "Germany",
      city: "Berlin",
      flag: "🇩🇪",
      timestamp: new Date(),
    },
    {
      ip: "33.22.11.100",
      reason: "SQL Injection attempt",
      country: "Russia",
      city: "Moscow",
      flag: "🇷🇺",
      timestamp: new Date(),
    },
    {
      ip: "101.202.103.44",
      reason: "Brute force login attempts",
      country: "China",
      city: "Shanghai",
      flag: "🇨🇳",
      timestamp: new Date(),
    },
    {
      ip: "22.33.44.55",
      reason: "XSS attack detected",
      country: "Italy",
      city: "Rome",
      flag: "🇮🇹",
      timestamp: new Date(),
    },
    {
      ip: "211.22.33.44",
      reason: "DoS attack detected",
      country: "South Korea",
      city: "Seoul",
      flag: "🇰🇷",
      timestamp: new Date(),
    },
    {
      ip: "55.66.77.88",
      reason: "SQL Injection attempt",
      country: "Netherlands",
      city: "Amsterdam",
      flag: "🇳🇱",
      timestamp: new Date(),
    },
    {
      ip: "44.33.22.11",
      reason: "Brute force login attempts",
      country: "Sweden",
      city: "Stockholm",
      flag: "🇸🇪",
      timestamp: new Date(),
    },
    {
      ip: "98.76.54.32",
      reason: "XSS attack detected",
      country: "South Africa",
      city: "Cape Town",
      flag: "🇿🇦",
      timestamp: new Date(),
    },
    {
      ip: "212.11.22.33",
      reason: "DoS attack detected",
      country: "Saudi Arabia",
      city: "Jeddah",
      flag: "🇸🇦",
      timestamp: new Date(),
    },
    {
      ip: "77.88.99.100",
      reason: "SQL Injection attempt",
      country: "Mexico",
      city: "Mexico City",
      flag: "🇲🇽",
      timestamp: new Date(),
    },
    {
      ip: "33.44.55.66",
      reason: "Brute force login attempts",
      country: "United Arab Emirates",
      city: "Dubai",
      flag: "🇦🇪",
      timestamp: new Date(),
    },
    {
      ip: "77.66.55.44",
      reason: "XSS attack detected",
      country: "Spain",
      city: "Barcelona",
      flag: "🇪🇸",
      timestamp: new Date(),
    },
    {
      ip: "88.99.77.66",
      reason: "DoS attack detected",
      country: "Turkey",
      city: "Istanbul",
      flag: "🇹🇷",
      timestamp: new Date(),
    },
    {
      ip: "44.55.66.77",
      reason: "SQL Injection attempt",
      country: "Argentina",
      city: "Buenos Aires",
      flag: "🇦🇷",
      timestamp: new Date(),
    },
    {
      ip: "33.22.11.10",
      reason: "Brute force login attempts",
      country: "Singapore",
      city: "Singapore",
      flag: "🇸🇬",
      timestamp: new Date(),
    },
    {
      ip: "123.234.56.78",
      reason: "XSS attack detected",
      country: "New Zealand",
      city: "Auckland",
      flag: "🇳🇿",
      timestamp: new Date(),
    },
    {
      ip: "55.44.33.22",
      reason: "DoS attack detected",
      country: "Portugal",
      city: "Lisbon",
      flag: "🇵🇹",
      timestamp: new Date(),
    },
    {
      ip: "77.88.99.101",
      reason: "SQL Injection attempt",
      country: "Malaysia",
      city: "Kuala Lumpur",
      flag: "🇲🇾",
      timestamp: new Date(),
    },
    {
      ip: "102.103.104.105",
      reason: "Brute force login attempts",
      country: "Pakistan",
      city: "Karachi",
      flag: "🇵🇰",
      timestamp: new Date(),
    },
    {
      ip: "202.203.204.205",
      reason: "XSS attack detected",
      country: "Indonesia",
      city: "Jakarta",
      flag: "🇮🇩",
      timestamp: new Date(),
    },
    {
      ip: "106.107.108.109",
      reason: "DoS attack detected",
      country: "Vietnam",
      city: "Hanoi",
      flag: "🇻🇳",
      timestamp: new Date(),
    },
  ]);

  console.log("Data added successfully 🎉");

  client.close();
  process.exit(0);
}

main();
